### PR TITLE
[Meteor] Fix default Node.js version + support 1.10

### LINKED ISSUE #37: [Meteor] Node.js version should be 12.6.x with Meteor 1.9
https://github.com/meteor/meteor/blob/devel/History.md#v192-2020-02-20

Issue for a customer here: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700004271

Issue introduced in #31. I don't see any reason not to use the latest LTS

### PR DESCRIPTION
**Pull request by EtienneM**
- [Meteor] Add support for Meteor 1.10.x
- [Meteor] Install Node.js 12.16.x with Meteor 1.9.x (and not 13.x)

Notify https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700004271 when in prod.

Fix #37

### CODE REVIEW

File: bin/meteor.sh [hunk 1]
```diff
@@ -17,8 +17,10 @@ get_meteor_minor_version() {
 # Format of .meteor/release file is METEOR@1.4.x-patchsomething
 meteor_node_version() {
   minor=$(get_meteor_minor_version)
-  if [ "$minor" -ge 9 ] ; then
-    echo "13.7.x"
+  if [ "$minor" -ge 10 ] ; then
+    echo "12.16.x"
```
Comment (johnsudaar) [inline bin/meteor.sh:21]: Why this special case ? This will fall in the if minor > 9

Comment (EtienneM) [reply bin/meteor.sh:21]: This is to explicitly add support for Meteor 1.10.x in case they change the Node.js version they want for this specific version. But maybe it's useless.

This is what has been done for Meteor 1.8 and 1.6.
